language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

php:
  - 5.6
  # aliased to a recent 7.x version
  - 7.0
  # aliased to a recent hhvm version
  - hhvm

env:
  - WP_VERSION=4.4.5 WP_MULTISITE=0
  - WP_VERSION=4.5.4 WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=0


#matrix:
#  include:
#    - php: 5.3
#      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - bash plugin/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit -c plugin/phpunit.xml.dist

after_success:
  - echo $push
  - chmod 600 /tmp/deploy_rsa
  - rsync -r --delete-after -e "ssh -p$pushport -i /tmp/deploy_rsa -o 'StrictHostKeyChecking no'" $TRAVIS_BUILD_DIR/plugin/ $pushuser@$puship:$pushpath
  - rm -rf /tmp/deploy_rsa

